spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application:
    name: mideaspcloud-config-midea-dev
    
---
spring:
  profiles: test
  application:
    name: mideaspcloud-config-midea-test